apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstdeployment
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: container
          image: gcr.io/google-samples/hello-app:1.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: first-service
  labels:
    app: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - port: 5000
      targetPort: 8080
