apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-deployment
  labels:
    app: api-2
spec:
  selector:
    matchLabels:
      app: api-2
  template:
    metadata:
      labels:
        app: api-2
    spec:
      containers:
        - name: container
          image: gcr.io/google-samples/hello-app:2.0
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: second-service
  labels:
    app: api-2
spec:
  type: NodePort
  selector:
    app: api-2
  ports:
    - port: 6000
      targetPort: 8080
