apiVersion: apps/v1
kind: Deployment
metadata:
  name: third-deployment
  labels:
    app: api-3
spec:
  selector:
    matchLabels:
      app: api-3
  template:
    metadata:
      labels:
        app: api-3
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: third-service
  labels:
    app: api-3
spec:
  type: NodePort
  selector:
    app: api-3
  ports:
    - port: 7000
      targetPort: 80
